### ISSUE TITLE
feat: functions

### ISSUE THREAD

**Issue by callumgran** [LytixDev/slash#25]
Allowing for simple functions would be greatly appreciated.

**Comment by LytixDev** [comment]
Suggestion for syntax. Using the `func` keyword as it is what POSIX sh uses now. Open for other keywords, or maybe even the omission of a keyword?
```
func foo(a, b, c) {
 ...
}
```
We should also support optional typing (see #33 and #32):
```
func foo(a: str, b: num, c: num) -> list {
 ...
}
```
We should also support default values.
```
func foo(a, b, c = 10) {
 ...
}
```
Default arguments can optionally be passed when calling the function. I think a regular argument must be passed, and not passing the correct amount of arguments should be an error.


As for functions itself, I think it makes sense to make them a first-class type. This means we can use it as any other object.

As for calling the functions, I see two realistic option here. The first option, which makes sense from a shell script perspective, would be to call it like any other shell command. The other option, perhaps more familiar to most, would be using parentheses. 
```
func concat(a: str, b: str) { ... }

foo "Hello" "World"
# or
foo("Hello", "World")
```

I think there are good arguments for and against both options.  Maybe we could support both? Or would that become confusing? we already support "methods" using `foo.bar()` syntax.

**Comment by LytixDev** [comment]
A basic function implementation has been added.

Example:
```rust
var fib_iterative = n {
    var a = 0
    var b = 1
    loop _ in 1..$n+1 {
        var c = $a + $b
        $a, $b = $b, $c
    }
    return $a
}

var fib_recursive = n {
    $n <= 1 && return $n
    return $fib_recursive($n - 1) + $fib_recursive($n - 2)
}

assert $fib_iterative(20) == 6_765
assert $fib_recursive(20) == 6_765

```
